### ISSUE TITLE
dimensions in datapoints filenames

### ISSUE THREAD

**Issue by buchslava** [Gapminder/ddf-validation#203]
dimensions in datapoints filenames support

for example, in ddf--datapoints--population--by--geo-usa-swe--year.csv

geo-usa-swe should be parsed as geo usa swe and they should be processed as separate concepts

**Comment by buchslava** [comment]
@jheeffer tell me please, are next cases possible?

1. ddf--datapoints--population-othermeasure1--by--geo-usa-swe--year.csv

second measure: 'othermeasure1'. I guess this case is correct

2. ddf--datapoints--population--by--usa-geo-swe--year.csv

entity domain on second position. I guess this case is correct

3. ddf--datapoints--population--by--usa-swe--year.csv

entity domain is missing (only values - swe and usa). I guess this case is wrong

4. ddf--datapoints--population--by--geo-otherdomain-usa-swe--year.csv

'otherdomain' is present apart from geo. I guess this case is wrong

Also question: should we check `ddf--datapoints--population--by--geo-usa-swe--year.csv`'s content as content in accordance with usa-swe values of geo? for example, should we raise an error if 'afg' value for example will be detected in the file?

**Comment by jheeffer** [comment]
@buchslava 

So this is about the file naming convention for **index-less** DDFcsv datapoint files. The convention makes it possible to infer from the filename what values of a dimension can be found in that file. It is described here: https://docs.google.com/document/d/1aynARjsrSgOKsO1dEqboTqANRD1O9u7J_xmxy8m5jW8/edit#heading=h.m6lqukls7quo

For your cases:

1. This is not supported. 
Reasoning: I presume you mean other indicator? If there are multiple indicators in one datapoint file they are separated by `--`, not `-`. See the link above. 
A single `-` in the list of indicators cóuld mean that this datapoint file only contains that value for that indicator. However, this is not part of the current spec because there's no real use case. 

2. This is not correct.
Reasoning: the dimension should always be the first in the list. After the concept, the values of that concept in the file could be listed, separated by `-`.

3. This is not correct
Reasoning: The concept should always be there to indicate what key-value pair is found in the file.

4. This is not correct
Reasoning: In the list of values after a concept, only values which are in the file.

Extra notes (also in the documentation):

* In the example `ddf--datapoints--population--by--geo-usa-swe--year.csv` the concept is an entity domain. However, the file naming convention can be used for any dimension, not just entity domains/sets. 
For example the following: `ddf--datapoints--population--by--geo--year-2011-2012-2013.csv`, has the population of countries for the years 2011, 2012 and 2013.
The entity domain/set is right now how Ola wants to separate the files, but we should allow this to work for any concept eventually. 

* If a list is given, the list has to be exhaustive. In other words:
 * the file cannot contain other values for the concept than given in the list
 * the file has to contain every value given in the list at least once

* Having the values of a concept in the filename is not mandatory. So a file with population per geo and year with only geo-values `swe` and `usa` could be called both  `ddf--datapoints--population--by--geo-usa-swe--year.csv` and  `ddf--datapoints--population--by--geo--year.csv`.

* The file naming conventions are only mandatory for indexless datasets. When a dataset has an index, file naming conventions are just guidelines. 

* The convention this issue is about makes it possible to read only a limited set of DDFcsv files when querying for specific values. E.g. `Select the population for keys geo, year where geo is usa`, does not have to look in files which have a geo-list in the filename which does not include usa.

* This file name convention covers a subset of the functionality of the [filter in DDFcsv index file](https://docs.google.com/document/d/1aynARjsrSgOKsO1dEqboTqANRD1O9u7J_xmxy8m5jW8/edit#heading=h.bfg8rjfkj6it).

**Comment by buchslava** [comment]
this issue was resolved by `datapackage creation` functionality (constraints)
